# Site settings
title: Things and stuff for the Internet
email: jomtung at gmail.com
description: "Welcome to my personal website.  Thanks for visiting.  Next time bring cookies."
baseurl: ""
url: "http://jomtung.github.io"

# Build settings
markdown: kramdown
permalink: pretty
encoding: UTF-8    
